# -*- coding: utf-8 -*-
"""7questions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgbuxuWZZaBWdDAHWRDLacjPIhO54feV
"""

import pandas as pd

# Project Euler question #14

longest_sequence = 0
starting_number = 0

# Check every number until 1 000 000
for i in range (1,1000000):
  current_number = i
  current_sequence = 1

  while current_number > 1:
    if current_number % 2 == 0:
      current_number = current_number / 2
    else:
      current_number = 3 * current_number + 1
    current_sequence += 1

# find a way to store if it is the lonest sequence we have found so far

  if current_sequence > longest_sequence:
    longest_sequence = current_sequence
    starting_number= i

print({starting_number})
print({longest_sequence})

# Project Euler finish question #7

count_primes = 0
prime_number = 2
last_prime = 0

while count_primes < 10001:
  is_prime = True

#check if our number is prime

  for i in range (2, int(prime_number**0.5)+1):
    if prime_number % i == 0:
      is_prime = False
      break

  if is_prime:
    count_primes += 1
    last_prime = prime_number
   # print(last_prime)

  prime_number += 1

print(last_prime)

# Write a function that takes a value and prints “even”, “odd”, “decimal”, or “not a number”.

def number_type(value):
 try:
  number = float(value)
  if number == int(number): # check if it is an integer
    integer_number = int(number)
    if integer_number % 2 == 0:
      return "even"
    else:
      return "odd"
  else:
    return "decimal"
 except (ValueError, TypeError):
    return "not a number"

  # any way to define if it is not a number

def number_type(x):
  if type(x) != int and type(x) != float:
    print("not a number")
  elif x % 2 == 0:
    print ("even")
  elif x % 2 == 1:
    print("odd")
  elif type(x) == float:
    print("decimal")
  else:
    print("no answer")

for i in [7,5.3,"John"]:
  number_type(i)

number_type(1.5)

print(number_type(2))

print(number_type(1.5))

print(number_type("AuPanthers"))

# Write a function that takes a US Zip Code (5 digits) from the user, and prints
# “Adelphi Zip Code” if it is equal to 11530. If it is a Zip Code other than 11530,
# print “Not Adelphi”. If a Zip Code is not entered (wrong amount of digits, wrong data type),
# print “Not a US Zip Code”

# find examples that would not work

zip_code_options = ["11530","11520", "1234","123456", "Vikto", None]

for zip_code in zip_code_options:
  if zip_code == "11530":
    print("Adelphi Zip Code")
  else:
    print("Not Adelphi")

  if zip_code == None:
    print("Not a US Zip Code")
  elif len(zip_code) != 5:
    print("Not a US Zip Code")

# Write a function that takes a list of integers and prints how many of the integers
# in the list are even integers.

def even_integers(integer_list):
  even_count = 0
  for number in integer_list:
    # Check if the number is an integer and even
    if isinstance(number, int) and number % 2 == 0:
      even_count += 1
  print({even_count})

even_integers([2,4,5,7,8])

# Write a function that prints all the even numbers between two numbers entered by the user.

start = int(input("start:"))
end = int(input("end:"))

for i in range(start, end+1):
  if i % 2 == 0:
    print(i)

# write a function that asks for name and then gives lenght of name

name = input("name:")

# print(len(name))

vowls = ["a","e","i","o","u"]
count = 0

for value in name:
  if value.lower() in vowls:
    count = count +1

print(count)

# Write a function that takes a list of integers from the user, and finds the length of the
# Collatz Sequence of each integer until it finds a Sequence that has a length greater
# than 14. (utilize your Collatz function from Project Euler question #14


longest_sequence = 0
starting_number = 0

# Check every number until 1 000 000
for i in range (1,1000000):
  current_number = i
  current_sequence = 1

  while current_number > 1:
    if current_number % 2 == 0:
      current_number = current_number / 2
    else:
      current_number = 3 * current_number + 1
    current_sequence += 1

# find a way to store if it is the lonest sequence we have found so far

  if current_sequence > longest_sequence:
    longest_sequence = current_sequence
    starting_number= i

  if current_sequence > 14:
    break
    print (current_sequence)

print({starting_number})
print({longest_sequence})