# -*- coding: utf-8 -*-
"""checkdivision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OLzu5GA7AG4mIgAfNbsPYBsq9dwzDCl
"""

import pandas as pd

# Write a function that accepts two parameters (x and y), checks if they are integers, and if they are integers then print the result of the floor division function of x and y.
# If they are not both integers, the function prints the data type of both x and y.

def check_division(x, y):
  if type(x)==int and type(y)==int:
    print(x // y)
    return x//y
  else:
    print(f"x is {type(x)} and y is {type(y)}")

x=check_division(5, 2)

x

check_division(5, 2.0)

check_division("hello", 3)

# Write a function that takes a list of names as a parameter. Then, inside the function use input to ask the user for their full name,
#  if it is longer than the average length of names in the list return True. Else, return False.

def name_lenght(names_list):

  # calculate total length and average length of names in the list
  total_length = sum(len(name) for name in names_list)
  average_lenght = total_length / len(names_list)

# get the first name
  your_first_name = input("What is your first name? ")
  name_lenght = len(your_first_name)

  if name_lenght > average_lenght:
    return True

  else:
    return False

names= ["Marko","Matias","Joacim","Spyros","Thomas"]
print(name_lenght(names))

# Write a function that starts by using input to ask for a 5 digit number, then your function turns that number into a string, and returns the 4th digit in the string.
# For example, if 13579 is entered, the function returns 7. If a 5 digit number is not entered by the user (maybe they enter a 7 digit number), print to them “incorrect value entered”.

def fourth_digit():
  number = input("Enter a 5 digit number: ")

  if len(number) == 5 and number.isdigit():
    print(number[3])
    return number[3]
  else:
    print("please enter valid number")
    fourth_digit()

fourth_digit()

fourth_digit()

from IPython.core.displaypub import CapturingDisplayPublisher
# Write a function that accepts two parameters (price and year). If the year is 2026, and the price is less than 30,000, the function should print “buy the car,
# it’s a good deal”. If the car is older than 2026, the criteria for buying the car for each year should be 30,000 minus 2000 * years old.
# So, a 2024 car should only print “buy the car” if the price is less than 26,000. If the price is not a good deal for the year,
# print how many dollars away from a good price the car is.

def buy_car(price, year):

  car_price = 30000
  depreciation_rate = 2000
  year_today = 2026

  if year > year_today:
    print(f"The car is from year {year}.")
    return

  elif year == year_today:
    good_deal = car_price
    if price < good_deal:
      print("Buy the car!")
    else:
      dollars_away = price - good_deal
      print(f"The car is {dollars_away} dollars away from a good price.")

  else:
    old_year = year_today - year
    good_deal = car_price - old_year * depreciation_rate
    if price < good_deal:
      print("Buy the car!")
    else:
      dollars_away = price - good_deal
      print(f"The car is {dollars_away} dollars away from a good price.")


#  else:
 #   old_year = year_today - year
  #  good_deal = car_price - old_year * depreciation_rate

#  else price < good_deal:
 #   print("Buy the car!")
 # else:
  #  dollars_away = price - good_deal
   # print(f"The car is {dollars_away} dollars away from a good price.")

buy_car(25000, 2024)

buy_car(25000, 2020)

# Write a function that takes a list of names, and prints the name, the length of the name,
# and the number of vowels in the name. If any of the names are not strings,
# just print the value and “not a string” and move on to the next.

def name_analysis(names):

  vowels = "aeiouAEIOU"
  for name in names:
    if type(name)== str:
      name_length2 = len(name)
      vowel_count = 0
      for value in name:
        if value in vowels:
          vowel_count += 1
      print(f"Name: {name}, Length: {name_length2}, Vowels: {vowel_count}")
    else:
      print(f"not a string")

     # vowels = "aeiouAEIOU"
  # count = 0

name_analysis(["Marko","Matias","Joacim","Spyros","Thomas"])

# Look into the random module in python. Use the random.randint method to create a function that
# simulates rolling a 6-sided die. So, you can call the function roll_die() and it prints a
# number from 1 to 6.
# write a function that tells you how many rolls it takes you to get 5 6s

import random

def roll_die():
  return random.randint(1,6)
 # print(result)

def roll_dice(number_of_dice):

  count_tries = 0
  dice_dict = {}
  result = False

  while result == False:
    for die in range(number_of_dice):
      dice_dict[die] = roll_die()
      print(dice_dict.values())
      count_tries += 1

      for v in dice_dict.values():
        if v == 6:
          result = True
        else:
          result = False





# erros: print results before 5 dice and stopping when last value (dice) = 6

roll_dice(5)

# Look into the random module in python. Use the random.randint method to create a function that
# simulates rolling a 6-sided die. So, you can call the function roll_die() and it prints a
# number from 1 to 6.
# write a function that tells you how many rolls it takes you to get 5 6s

import random

def roll_die():
  return random.randint(1,6)
 # print(result)

def roll_dice(number_of_dice=5):

  count_tries = 0
  sixes_rolled = 0

  while sixes_rolled < 5:
    # roll it all 5 times and store in a list/ dictonary
    outcomes = []
    for i in range(5):
      outcomes.append(roll_die())

    count_tries += 1
    print(outcomes)


    if sum(outcomes) < 30:
      sixes_rolled = 4
    else:
      sixes_rolled = 5


  print(count_tries)
  return count_tries

roll_dice()



  #  for die in range(number_of_dice):
    #  dice_dict[die] = roll_die()
     # print(dice_dict.values())
      #count_tries += 1

    #  for v in dice_dict.values():
     #   if v == 6:
      #    result = True
       # else:
        #  result = False





# for next week: update number of dice parameter
# test if it works with 10 dice

import random

def roll_die():
    return random.randint(1, 6)

def roll_dice(number_of_dice=5):
    count_tries = 0

    while True:
        # roll all dice
        outcomes = [roll_die() for _ in range(number_of_dice)]
        count_tries += 1

        print(outcomes)

        # count how many sixes were rolled
        sixes_rolled = outcomes.count(6)

        # check if all dice are 6
        if sixes_rolled == number_of_dice:
            break

    print("Total tries:", count_tries)
    return count_tries

roll_dice()

roll_dice()

vegetables = ["carrot", "corn", "broccoli","asparagus"]

del vegetables[1:4]

vegetables

number=[1,2,3,4,5,6 ]

even_squared=[n*n for n in number if n % 2 == 0]

print(even_squared)

# write a function that takes 3 parameters, and returns the sum.
# if the function can't sum the parameter for any reason, print,
# that the inputs were invalid. Regardeless, of what happens,
# print, got to the end.
# parameter = (x,y,z) put in after

def parameter_function(x,y,z):

  try:
    return x+y+z
  except:
    print("invalid input")
  finally:
    print("got to the end")

parameter_function(3,5,9)

parameter_function(2,3,"hello")

# without a function, make a dictionary that has the course I am enrolled in as keys,
# and the value for each of these keys will be grades I received so far. can be letters or numbers

courses_grades={"Accounting":94,
                "Managerial Finance":91,
                "Drawing":[76,"B+",91]}

courses_grades