# -*- coding: utf-8 -*-
"""longestsequence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epqqBSH0uBgHwPnlAavAldv5RfUtTvzg
"""

longest_sequence = 0
starting_number = 0

# Check every number until 1 000 000
for i in range (1,1000000):
  current_number = i
  current_sequence = 1

  while current_number > 1:
    if current_number % 2 == 0:
      current_number = current_number / 2
    else:
      current_number = 3 * current_number + 1
    current_sequence += 1

# find a way to store if it is the lonest sequence we have found so far

  if current_sequence > longest_sequence:
    longest_sequence = current_sequence
    starting_number= i

print(f"The starting number that produces the longest sequence is: {starting_number}")
print(f"The length of the longest sequence is: {longest_sequence}")

longest_sequence = 0
starting_number = 0

# Check every number until 1 000 000
for i in range (1,1000000):
  current_number = i
  current_sequence = 1

  while current_number > 1:
    if current_number % 2 == 0:
      current_number = current_number / 2
    else:
      current_number = 3 * current_number + 1
    current_sequence += 1

# find a way to store if it is the lonest sequence we have found so far

  if current_sequence > longest_sequence:
    longest_sequence = current_sequence
    starting_number= i

print(f"The starting number that produces the longest sequence is: {starting_number}")
print(f"The length of the longest sequence is: {longest_sequence}")

# Write a function that takes a value and prints “even”, “odd”,
# “decimal”, or “not a number”.

def classify_number(value):
  try:
    num = float(value)
    if num == int(num):
      # It's an integer (e.g., 5, 5.0)
      int_num = int(num)
      if int_num % 2 == 0:
        return "even"
      else:
        return "odd"
    else:
      # It's a float with a non-zero decimal part
      return "decimal"
  except (ValueError, TypeError):
    # Cannot convert to a number
    return "not a number"

# Test cases
print(f"5: {classify_number(5)}")
print(f"-2: {classify_number(-2)}")
print(f"0: {classify_number(0)}")
print(f"3.14: {classify_number(3.14)}")
print(f"-0.5: {classify_number(-0.5)}")
print(f"4.0: {classify_number(4.0)}")
print(f"'hello': {classify_number('hello')}")
print(f"'10': {classify_number('10')}")
print(f"'7.2': {classify_number('7.2')}")
print(f"None: {classify_number(None)}")

def classify_zip_code(zip_code_input):
  # Check if the input is a string and consists only of digits
  if isinstance(zip_code_input, str) and zip_code_input.isdigit():
    # Check if the length is exactly 5
    if len(zip_code_input) == 5:
      if zip_code_input == "11530":
        print("Adelphi Zip Code")
      else:
        print("Not Adelphi")
    else:
      print("Not a US Zip Code") # Wrong amount of digits
  else:
    print("Not a US Zip Code") # Wrong data type or non-digit characters

# Example of how to use the function with user input
user_input = input("Please enter a 5-digit US Zip Code: ")
classify_zip_code(user_input)

# Test cases for demonstration
print("\n--- Test Cases ---")
classify_zip_code("11530") # Adelphi Zip Code
classify_zip_code("90210") # Not Adelphi
classify_zip_code("1234")  # Not a US Zip Code (too short)
classify_zip_code("123456") # Not a US Zip Code (too long)
classify_zip_code("abcde") # Not a US Zip Code (wrong data type/characters)
classify_zip_code(12345) # Not a US Zip Code (wrong data type, even if numeric)

# Test cases for zip code classification without a function or user input

zip_codes_to_test = ["11530", "90210", "1234", "123456", "abcde", 12345, None]

for zip_code_input in zip_codes_to_test:
  print(f"Testing: {zip_code_input}")
  # Check if the input is a string and consists only of digits
  if isinstance(zip_code_input, str) and zip_code_input.isdigit():
    # Check if the length is exactly 5
    if len(zip_code_input) == 5:
      if zip_code_input == "11530":
        print("Adelphi Zip Code")
      else:
        print("Not Adelphi")
    else:
      print("Not a US Zip Code") # Wrong amount of digits
  else:
    print("Not a US Zip Code") # Wrong data type or non-digit characters
  print("--------------------")

# Alternative solution without using isinstance()

zip_code_options = ["11530","11520", "1234","123456", "Vikto", None, 12345] # Added 12345 for testing

for zip_code in zip_code_options:
  print(f"Testing: {zip_code}")
  is_valid_zip_format = False

  try:
    # Attempt to use string methods. If zip_code is not a string, this will raise an AttributeError.
    if len(zip_code) == 5 and zip_code.isdigit():
      is_valid_zip_format = True
  except AttributeError: # Catches if zip_code doesn't have .isdigit() or len() (e.g., None, int)
    pass # is_valid_zip_format remains False
  except TypeError: # Catches issues with len() on types like None
    pass # is_valid_zip_format remains False

  if is_valid_zip_format:
    if zip_code == "11530":
      print("Adelphi Zip Code")
    else:
      print("Not Adelphi")
  else:
    print("Not a US Zip Code") # Covers wrong length, non-digit characters, and non-string types
  print("--------------------")

def count_even_integers(int_list):
  even_count = 0
  for number in int_list:
    # Check if the number is an integer and even
    if isinstance(number, int) and number % 2 == 0:
      even_count += 1
  print(f"Number of even integers in the list: {even_count}")

# Test cases
print("--- Test Case 1 ---")
my_list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
count_even_integers(my_list_1) # Expected: 5

print("\n--- Test Case 2 ---")
my_list_2 = [1, 3, 5, 7, 9]
count_even_integers(my_list_2) # Expected: 0

print("\n--- Test Case 3 ---")
my_list_3 = [2, 4, 6, 8, 10]
count_even_integers(my_list_3) # Expected: 5

print("\n--- Test Case 4 ---")
my_list_4 = []
count_even_integers(my_list_4) # Expected: 0

print("\n--- Test Case 5 ---")
my_list_5 = [-2, 0, 5, -10, 7.5, 'hello'] # Includes non-integers for robustness
count_even_integers(my_list_5) # Expected: 3 (for -2, 0, -10)

# Write a function that takes a US Zip Code (5 digits) from the user, and prints
# “Adelphi Zip Code” if it is equal to 11530. If it is a Zip Code other than 11530,
# print “Not Adelphi”. If a Zip Code is not entered (wrong amount of digits, wrong data type),
# print “Not a US Zip Code”

# find examples that would not work

zip_code_options = ["11530","11520", "1234","123456", "Vikto", None]

for zip_code in zip_code_options:
  print(f"Testing: {zip_code}") # Added for clarity
  if isinstance(zip_code, str) and zip_code.isdigit():
    if len(zip_code) == 5:
      if zip_code == "11530":
        print("Adelphi Zip Code")
      else:
        print("Not Adelphi")
    else:
      print("Not a US Zip Code") # Wrong amount of digits
  else:
    print("Not a US Zip Code") # Wrong data type or non-digit characters
  print("--------------------") # Added for clarity

# Write a function that takes a US Zip Code (5 digits) from the user, and prints
# “Adelphi Zip Code” if it is equal to 11530. If it is a Zip Code other than 11530,
# print “Not Adelphi”. If a Zip Code is not entered (wrong amount of digits, wrong data type),
# print “Not a US Zip Code”

# find examples that would not work

zip_code_options = ["11530","11520", "1234","123456", "Vikto", None]

for zip_code in zip_code_options:
  print(f"Testing: {zip_code}") # Added for clarity
  if isinstance(zip_code, str) and zip_code.isdigit():
    if len(zip_code) == 5:
      if zip_code == "11530":
        print("Adelphi Zip Code")
      else:
        print("Not Adelphi")
    else:
      print("Not a US Zip Code") # Wrong amount of digits
  else:
    print("Not a US Zip Code") # Wrong data type or non-digit characters
  print("--------------------") # Added for clarity



def count_even_integers(int_list):
  even_count = 0
  for number in int_list:
    # Check if the number is an integer and even
    if isinstance(number, int) and number % 2 == 0:
      even_count += 1
  print(f"Number of even integers in the list: {even_count}")

print[2,4,,6,8,10]

count_even_integers([2, 4, 6, 8, 10])

def print_even_numbers_in_range():
  try:
    # Get input from the user
    num1_str = input("Enter the first number: ")
    num2_str = input("Enter the second number: ")

    # Convert inputs to integers
    num1 = int(num1_str)
    num2 = int(num2_str)

    # Ensure num1 is the smaller number and num2 is the larger number
    if num1 > num2:
      num1, num2 = num2, num1 # Swap them if num1 is greater

    print(f"Even numbers between {num1} and {num2} (inclusive):")
    found_even = False
    for i in range(num1, num2 + 1):
      if i % 2 == 0:
        print(i)
        found_even = True

    if not found_even:
        print("No even numbers found in this range.")

  except ValueError:
    print("Invalid input. Please enter valid integers.")
  except Exception as e:
    print(f"An unexpected error occurred: {e}")

# Call the function to execute it
print_even_numbers_in_range()

"""### Explanation:

1.  **`print_even_numbers_in_range()` Function:** This function encapsulates the logic.
2.  **User Input:** It prompts the user to `Enter the first number:` and `Enter the second number:`, storing them as strings.
3.  **Type Conversion:** `int()` is used to convert the input strings into integers. A `try-except ValueError` block is used to catch non-integer inputs.
4.  **Order Check:** `if num1 > num2:` ensures that the first number is always less than or equal to the second number, making the `range()` function work correctly. It swaps them if necessary.
5.  **Iteration:** A `for` loop iterates through all numbers from `num1` to `num2` (inclusive, hence `num2 + 1`).
6.  **Even Number Check:** `if i % 2 == 0:` checks if the current number `i` is even (i.e., its remainder when divided by 2 is 0).
7.  **Printing Even Numbers:** If a number is even, it's printed. If no even numbers are found, a message is displayed.
8.  **Error Handling:** Includes `try-except` blocks for `ValueError` (for invalid number input) and a general `Exception` for other unexpected issues.
"""

def print_even_numbers_short():
  try:
    num1 = int(input("Enter the first number: "))
    num2 = int(input("Enter the second number: "))

    # Use min and max for concise range ordering
    start = min(num1, num2)
    end = max(num1, num2)

    even_numbers = [str(i) for i in range(start, end + 1) if i % 2 == 0]

    if even_numbers:
      print(f"Even numbers between {start} and {end} (inclusive):\n" + "\n".join(even_numbers))
    else:
      print(f"No even numbers found in this range.")

  except ValueError:
    print("Invalid input. Please enter valid integers.")

# Call the function to execute it
print_even_numbers_short()

"""### Explanation of Changes:

1.  **`min(num1, num2)` and `max(num1, num2)`:** This replaces the explicit `if num1 > num2: num1, num2 = num2, num1` swap, making the range setup more compact.
2.  **List Comprehension:** Instead of a `for` loop with `print(i)` inside, a list comprehension `[str(i) for i in range(start, end + 1) if i % 2 == 0]` is used to collect all even numbers as strings.
3.  **`'\n'.join(even_numbers)`:** This combines the collected even numbers into a single string, with each number separated by a newline character, which is then printed in one go. This is a more Pythonic way to print items on separate lines after collecting them.
4.  **Simplified `if even_numbers:` check:** This directly checks if the list of even numbers is empty to determine if the "No even numbers found" message should be printed.
"""

# Test cases
print("--- Test Case 1 ---")
my_list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
count_even_integers(my_list_1) # Expected: 5

print("\n--- Test Case 2 ---")
my_list_2 = [1, 3, 5, 7, 9]
count_even_integers(my_list_2) # Expected: 0

print("\n--- Test Case 3 ---")
my_list_3 = [2, 4, 6, 8, 10]
count_even_integers(my_list_3) # Expected: 5

print("\n--- Test Case 4 ---")
my_list_4 = []
count_even_integers(my_list_4) # Expected: 0

print("\n--- Test Case 5 ---")
my_list_5 = [-2, 0, 5, -10, 7.5, 'hello'] # Includes non-integers for robustness
count_even_integers(my_list_5) # Expected: 3 (for -2, 0, -10)

print([2,4,6,8,10])