# -*- coding: utf-8 -*-
"""NameAnalysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9vj0F1R9NUCnPGUoEU-6r4BCRr0d8Fa
"""



def name_analysis_corrected(names):
  vowels = "aeiouAEIOU"
  for name in names:
    if isinstance(name, str):
      name_length = len(name) # Corrected typo: lenght -> length
      vowel_count = 0 # Reset vowel count for each name
      for char in name: # Changed 'value' to 'char' for clarity
        if char in vowels: # Corrected: value() -> char
          vowel_count += 1 # Simplified increment
      print(f"Name: {name}, Length: {name_length}, Vowels: {vowel_count}")
    else:
      print(f"Value: {name} - not a string") # Added handling for non-string items

# Example usage:
print("--- Test Case: Mixed list ---")
my_names_to_analyze = ["Alice", "Bob", "Charlie", 123, "Eve", None, "Frank", "Python"]
name_analysis_corrected(my_names_to_analyze)

name_analysis_corrected("Viktor")

import random

def roll_die():
  """Simulates rolling a 6-sided die and prints the result."""
  result = random.randint(1, 6)
  print(f"You rolled a: {result}")

# Example usage:
print("Rolling the die a few times:")
roll_die()
roll_die()
roll_die()

def fourth_digit():
    """
    Asks the user for a 5-digit number, validates the input,
    and returns the 4th digit if valid. Otherwise, prints an error.
    """
    number_str = input("Enter a 5-digit number: ")

    if len(number_str) == 5 and number_str.isdigit():
        # The 4th digit is at index 3 (0-indexed)
        return number_str[3]
    else:
        print("incorrect value entered")
        return None # Or raise an error, depending on desired behavior

# Example usage:
print("--- Test Case 1: Valid 5-digit number ---")
result1 = fourth_digit()
if result1 is not None:
    print(f"The 4th digit is: {result1}")

print("\n--- Test Case 2: Invalid (not 5 digits) ---")
result2 = fourth_digit()
if result2 is not None:
    print(f"The 4th digit is: {result2}")

print("\n--- Test Case 3: Invalid (contains non-digits) ---")
result3 = fourth_digit()
if result3 is not None:
    print(f"The 4th digit is: {result3}")

def evaluate_car_deal(price, year):
    """
    Evaluates if a car's price is a good deal based on its year.

    Args:
        price (int or float): The price of the car.
        year (int): The year the car was made.
    """
    base_price_threshold = 30000
    depreciation_per_year = 2000
    reference_year = 2026

    if year > reference_year:
        print(f"The car is from year {year}. This function only evaluates cars up to {reference_year}.")
        return

    if year == reference_year:
        good_deal_price = base_price_threshold
    else:
        years_older = reference_year - year
        good_deal_price = base_price_threshold - (depreciation_per_year * years_older)

    if price < good_deal_price:
        print(f"buy the car, it’s a good deal (target price: ${good_deal_price:,})")
    else:
        dollars_away = price - good_deal_price
        print(f"The car is ${dollars_away:,} dollars away from a good price (target price: ${good_deal_price:,})")

# Example Usage:
print("--- Test Case 1: 2026 car, good deal ---")
evaluate_car_deal(29000, 2026)

print("\n--- Test Case 2: 2026 car, not a good deal ---")
evaluate_car_deal(31000, 2026)

print("\n--- Test Case 3: 2024 car, good deal (30000 - 2*2000 = 26000) ---")
evaluate_car_deal(25000, 2024)

print("\n--- Test Case 4: 2024 car, not a good deal ---")
evaluate_car_deal(27000, 2024)

print("\n--- Test Case 5: 2020 car (30000 - 6*2000 = 18000) ---")
evaluate_car_deal(18500, 2020)

print("\n--- Test Case 6: Car from a future year ---")
evaluate_car_deal(20000, 2027)

def analyze_names(names_list):
    """
    Analyzes a list of items. For each string item, it prints the name, its length,
    and the number of vowels. For non-string items, it prints the value and 'not a string'.
    """
    vowels = "aeiouAEIOU"
    for item in names_list:
        if isinstance(item, str):
            name_length = len(item)
            vowel_count = sum(1 for char in item if char in vowels)
            print(f"Name: {item}, Length: {name_length}, Vowels: {vowel_count}")
        else:
            print(f"Value: {item} - not a string")

# Example usage:
print("--- Test Case 1: Mixed list ---")
my_names = ["Alice", "Bob", "Charlie", 123, "Eve", None, "Frank", "Python"]
analyze_names(my_names)

print("\n--- Test Case 2: All strings ---")
alias_names = ["Alpha", "Beta", "Gamma"]
analyze_names(alias_names)

print("\n--- Test Case 3: All non-strings ---")
mixed_list = [1, 2.5, True, {"key": "value"}]
analyze_names(mixed_list)