# -*- coding: utf-8 -*-
"""palindrome.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12T6030vqQ4uKYNjVBCMsrxGwX5YyYOMn
"""

def is_palindrome():

  is_palindrome = str(input("Enter your word:"))

  if is_palindrome.lower().replace(" ","") == is_palindrome.lower().replace(" ","")[::-1]:
    return True

  else:
    return False

is_palindrome()

is_palindrome()