# -*- coding: utf-8 -*-
"""Project Euler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oB7PT7j5rzaf2EiERv4R2yfUwPH6Punc
"""

2+2

2**3

import pandas as pd

pip install nba_history

import random

random. randint(1,100)

# Among the first 487 thousand square numbers, what is the sum of all the odd squares?

# first, find the first 487 thousand square numbers
number_of_squares = 0
current_number = 1
squares_list = []

while number_of_squares < 487000:
  squares_list.append(current_number*current_number)
  current_number = current_number + 1
  number_of_squares = number_of_squares + 1

# find another square number
#for i in squares_list:
 # if i % 2 == 0:
  #  squares_list.remove(i)
squares_list = squares_list[::2]

# filter for only odd numbers
sum(squares_list)

# then sum them, and print

# Find the sum of all the multiples of 3 or 5 below 1000

# first, find all multiples of 3 or 5 below 1000
sum_of_multiples = sum(i for i in range(1000)
if i % 3 == 0 or i % 5 == 0)

# then sum them, and print
print(sum_of_multiples)

# Find the sum of all the multiples of 3 or 5 below 1000

def find_multiple(x, y, range_number):
  sum_of_multiples = sum(i for i in range(range_number)
  if i % x == 0 or i % y == 0)

  print(sum_of_multiples)

find_multiple(x = 3,
              y = 5,
              range_number = 1000)

# Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum

# Find the sum of the squares of the first one hundred natural numbers
sum_of_squares = sum(i**2 for i in range(1, 101))

# Find the square of the sum of the first one hundred numbers
square_of_sum = sum(range(1, 101))**2

# Subtract the sum of the squares from the square of the sum, and print
difference = square_of_sum - sum_of_squares
print(difference)

# Find the sum of all the primes below two million.

# Find all prime numbers below two million
def is_prime(x):
  if x % 2 == 0:
    return False

  elif x % 3 == 0:
    return False

  elif x % 5 == 0:
    return False

  elif x % 7 == 0:
    return False

  else:
    return True

# 1. make a function to test if a number is prime
prime_list = []

for i in range(2, 2000000):
  if is_prime(x = i) == True:
    prime_list.append(i)

# 2. use that function on every natural number below 2M
# store these in a list
sum(prime_list)

# Find the sum of all the primes below two million.

# Find all prime numbers below two million
def is_prime(x):
  if x < 2:
    return False

  elif x == 2:
    return False

  elif x % 2 == 0:
    return False

  for i in range(3, int(x**0.5)+1, 2):
    if x % i == 0:
      return False

  else:
    return True

# 1. make a function to test if a number is prime
prime_list = []

for i in range(2, 2000000):
  if is_prime(x = i) == True:
    prime_list.append(i)

# 2. use that function on every natural number below 2M
# store these in a list
sum(prime_list)

# Find the sum of all the primes below two million.

# Find all prime numbers below two million
def is_prime(x):

  def is_prime(x):

    if x < 2:
      return False

  for i in range(2, int(x**0.5) + 1):
    if x % i == 0:
      return False

  return True

# 1. make a function to test if a number is prime


# 2. use that function on every natural number below 2M
# store these in a list
sum(prime_list)

# What is the greatest product of four adjacent numbers in the same direction (up, down, left, right, or diagonally) in the 20x20 grid? (11)

def adjacent_num_product(a, b, c, d):
  return a*b*c*d

def check_matrix(matrix):




08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
24 55 58 05 66 73 99 26 97 17 78 78 96 83 14 88 34 89 63 72
21 36 23 09 75 00 76 44 20 45 35 14 00 61 33 97 34 31 33 95
78 17 53 28 22 75 31 67 15 94 03 80 04 62 16 14 09 53 56 92
16 39 05 42 96 35 31 47 55 58 88 24 00 17 54 24 36 29 85 57
86 56 00 48 35 71 89 07 05 44 44 37 44 60 21 58 51 54 17 58
19 80 81 68 05 94 47 69 28 73 92 13 86 52 17 77 04 89 55 40
04 52 08 83 97 35 99 16 07 97 57 32 16 26 26 79 33 27 98 66
88 36 68 87 57 62 20 72 03 46 33 67 46 55 12 32 63 93 53 69
04 42 16 73 38 25 39 11 24 94 72 18 08 46 29 32 40 62 76 36
20 69 36 41 72 30 23 88 34 62 99 69 82 67 59 85 74 04 36 16
20 73 35 29 78 31 90 01 74 31 49 71 48 86 81 16 23 57 05 54
01 70 54 71 83 51 54 69 16 92 33 48 61 43 52 01 89 19 67 48

# find the four biggest adjacent numbers in the same direction


# sum them, and print

# What is the largest prime factor of the number 600851475143 ?

number = 600851475143
factor = 2

# Check if the number divides evenly, and check if it divides and keeps it as a whole number

while number > 1:
  if number % factor == 0:
    number = number // factor

  else:
    factor = factor +1

print(factor)

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr

x="Class #2"

x

class_num = 3

f"Class #{class_num}"

z= f"Class #{2*2}"

type(z)

type(False)

fruit=["apple","z","orange"]

fruit[0]

fruit[-1]

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

limit = 4000000

a = 1
b = 2
even_sum = 0

while a <= limit:
    if a % 2 == 0:
        even_sum += a

    a, b = b, a + b

print(even_sum)