# -*- coding: utf-8 -*-
"""sum_of_squares_PE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzn7CEMwQxpTscrNsuhuedLbCb6O7P_l
"""

# among the first 487K square numbers, what is the sum of the odd squares?

# NEW SOLUTION

# create a function, so it's dynamic based on user inputs
def sum_of_squares(restrictions, number_of_squares):

  # create an empty list of squares
  squares_list = []

  # continue adding squares to the list until number_of_squares is met
  while len(squares_list) < number_of_squares:
    squares_list.append((len(squares_list) + 1) * (len(squares_list) + 1))

  # filter the list based on restrictions you set
  if restrictions == "odd":
    squares_list = squares_list[::2]
  elif restrictions == "even":
    squares_list = squares_list[1::2]

  # print the sum of the squares list
  print(sum(squares_list))


# now, run the dynamic function you just created
sum_of_squares(restrictions="odd", number_of_squares = 487000)

# among the first 487K square numbers, what is the sum of the odd?

# INITIAL SOLUTION

# first, find the 487K square numbers
number_of_squares = 0
current_number = 1
squares_list = []

while number_of_squares < 487000:
  squares_list.append(current_number * current_number)
  current_number = current_number + 1
  number_of_squares = number_of_squares + 1

# filter for only odd squares
squares_list = squares_list[::2]

#for i in squares_list:
#  if i % 2 == 0:
#    squares_list.remove(i)

# then sum them, and print
#sum_of_squares = 0
#for i in squares_list:
#  sum_of_squares = sum_of_squares + i

sum(squares_list)

